import { create } from 'zustand';

const useRegisterStore = create((set) => ({
  profileImage: {},
  name: '',
  cpf: '',
  email: '',
  password: '',
  confirmPassword: '',
  tel: '',
  confirmTel: '',
  cep: '',
  address: '',
  number: '',
  neighborhood: '',
  complement: '',
  uf: '',
  city: '',
  reference: '',
  setProfileImage: (data) => set(() => ({ profileImage: data })),
  setName: (e) => set(() => ({ name: e.target.value })),
  setCpf: (value) => set(() => ({ cpf: value })),
  setEmail: (e) => set(() => ({ email: e.target.value })),
  setPassword: (e) => set(() => ({ password: e.target.value })),
  setConfirmPassword: (e) => set(() => ({ confirmPassword: e.target.value })),
  setTel: (value) => set(() => ({ tel: value })),
  setConfirmTel: (value) => set(() => ({ confirmTel: value })),
  setCep: (value) => set(() => ({ cep: value })),
  setAddress: (e) => set(() => ({ address: e.target.value })),
  setNumber: (e) => set(() => ({ number: e.target.value })),
  setNeighborhood: (e) => set(() => ({ neighborhood: e.target.value })),
  setComplement: (e) => set(() => ({ complement: e.target.value })),
  setUf: (e) => set(() => ({ uf: e.target.value })),
  setCity: (e) => set(() => ({ city: e.target.value })),
  setReference: (e) => set(() => ({ reference: e.target.value })),
  isSubmitting: false,
  submitting: () => set(() => ({ isSubmitting: true })),
  notSubmitting: () => set(() => ({ isSubmitting: false })),
  isRegisterCompleted: false,
  registerComplete: () => set(() => ({ isRegisterCompleted: true })),
  registerNotComplete: () => set(() => ({ isRegisterCompleted: false })),
}));

export default useRegisterStore;